const $=id=>document.getElementById(id),c=$('canvas'),ctx=c.getContext('2d');let photo=null,points=[],coin=[],closed=false,mode='manual',zoom=1,history=[],drag=-1,name='pattern';
let seed=null, detectedLight=false, validTrace=true, timer=null;
function status(s){$('status').textContent=s}function save(){history.push({points:structuredClone(points),coin:structuredClone(coin),closed,seed:seed&&{...seed},validTrace,detectedLight,mode,threshold:$('threshold').value,polarity:$('polarity').value,smooth:$('smooth').value});if(history.length>50)history.shift()}
function setMode(m){clearTimeout(timer);mode=m;guide();for(const id of ['calibrate','manual','auto','edit'])$(id).classList.toggle('active',id===m)}
function scale(){const circle=Geometry.circleThrough3(coin);return circle?20/(2*circle.radius):null}
function draw(){guide();if(!photo)return;ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(photo,0,0);ctx.lineWidth=2/zoom;ctx.strokeStyle=validTrace?'#00a88e':'#d88b22';ctx.fillStyle='#00a88e22';if(points.length){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(closed){ctx.closePath();ctx.fill()}ctx.stroke();ctx.fillStyle='white';for(const p of (mode==='edit'||mode==='manual'?points:[])){ctx.beginPath();ctx.arc(p.x,p.y,3.5/zoom,0,Math.PI*2);ctx.fill();ctx.stroke()}}ctx.strokeStyle='#f1a52f';coin.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,5/zoom,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#bd7100';ctx.font=16/zoom+'px sans-serif';ctx.fillText(String(i+1),p.x+8/zoom,p.y-8/zoom)});const circle=Geometry.circleThrough3(coin);if(circle){ctx.beginPath();ctx.arc(circle.x,circle.y,circle.radius,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#bd7100';ctx.font=14/zoom+'px sans-serif';ctx.fillText('直径 20 mm',circle.x+circle.radius+8/zoom,circle.y)}const s=scale();$('scale').textContent=s?`縮尺設定済み · 1 px = ${s.toFixed(4)} mm`:'縮尺未設定 · 1円玉 = 20 mm';const b=points.length?Geometry.bounds(points):null;$('width').textContent=s&&b?((b.maxX-b.minX)*s).toFixed(2)+' mm':'—';$('height').textContent=s&&b?((b.maxY-b.minY)*s).toFixed(2)+' mm':'—';$('export').disabled=!(s&&closed&&validTrace&&points.length>2&&Geometry.area(points)>.01)}
function setZoom(z){zoom=Math.max(.1,Math.min(8,z));c.style.width=c.width*zoom+'px';c.style.height=c.height*zoom+'px';$('zoomLabel').textContent=Math.round(zoom*100)+'%';draw()}
function fit(){if(photo)setZoom(Math.min(($('viewport').clientWidth-2)/c.width,($('viewport').clientHeight-2)/c.height))}
function load(img,title){clearTimeout(timer);adjusting=false;photo=img;c.width=img.width;c.height=img.height;points=[];coin=[];closed=false;history=[];seed=null;validTrace=true;$('polarity').value='auto';name=title.replace(/\.[^.]+$/,'');$('filename').textContent=title;$('empty').style.display='none';c.style.display='block';setMode('auto');fit();status('対象物の内側をクリックしてください。自動トレースは選択済みです。')}
$('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const image=await createImageBitmap(file);const ratio=Math.min(1,2200/Math.max(image.width,image.height));const off=document.createElement('canvas');off.width=Math.round(image.width*ratio);off.height=Math.round(image.height*ratio);const cx=off.getContext('2d');cx.fillStyle='white';cx.fillRect(0,0,off.width,off.height);cx.drawImage(image,0,0,off.width,off.height);image.close();load(off,file.name)}catch{status('画像を読み込めません。JPG・PNG・WebP・BMPで保存して選び直してください。')}e.target.value=''};
$('demo').onclick=()=>{const d=document.createElement('canvas');d.width=1000;d.height=700;const x=d.getContext('2d');x.fillStyle='#f6f2e9';x.fillRect(0,0,1000,700);x.fillStyle='#445c69';x.beginPath();x.moveTo(220,150);x.lineTo(550,150);x.quadraticCurveTo(660,150,660,260);x.lineTo(660,450);x.lineTo(480,450);x.lineTo(480,530);x.lineTo(220,530);x.closePath();x.fill();x.fillStyle='#bbc1c4';x.beginPath();x.arc(815,470,50,0,Math.PI*2);x.fill();x.strokeStyle='#858e93';x.lineWidth=3;x.stroke();x.fillStyle='#69777d';x.font='42px serif';x.textAlign='center';x.fillText('1',815,485);x.font='15px sans-serif';x.fillText('1円玉 / 直径20 mm',815,550);load(d,'サンプル.png');status('まず青い物の中央をクリックしてください。緑の線が出たら「次へ」でサイズ合わせに進みます。')};
for(const m of ['calibrate','manual','auto','edit'])$(m).onclick=()=>{if(!photo)return status('先に写真を読み込んでください。');if(m==='manual'&&closed){save();points=[];closed=false;seed=null;validTrace=true;}if(m==='calibrate'){save();coin=[];}if(m==='edit'){seed=null;validTrace=true;}setMode(m);draw();status({calibrate:'① 1円玉の円周上の1点目をクリックしてください。離れた3点を指定します。',manual:'輪郭に沿って点をクリック。最後に「輪郭を閉じる」を押してください。',auto:'対象物の内側をクリックすると、つながった領域の外周を抽出します。穴は抽出しません。',edit:'輪郭上の白い頂点をドラッグして調整できます。'}[m])};
function position(e){const r=c.getBoundingClientRect();return{x:Math.max(0,Math.min(c.width,(e.clientX-r.left)/zoom)),y:Math.max(0,Math.min(c.height,(e.clientY-r.top)/zoom))}}
c.onpointerdown=e=>{if(!photo)return;clearTimeout(timer);const p=position(e);if(mode==='edit'){drag=points.findIndex(v=>Math.hypot(v.x-p.x,v.y-p.y)<10/zoom);if(drag>=0){save();c.setPointerCapture(e.pointerId)}return}if(mode==='calibrate'){if(coin.some(v=>Math.hypot(p.x-v.x,p.y-v.y)<5))return status('点が近すぎます。円周上の離れた場所を指定してください。');if(coin.length===2&&!Geometry.circleThrough3([...coin,p]))return status('この3点では安定した円を作れません。3点目を円周上の別の場所に指定してください。');save();coin.push(p);if(coin.length===3){setMode(closed?'edit':'auto');status('3点から円を作成しました。オレンジの円が1円玉に合っているか確認してください。')}else status(coin.length===1?'② 円周上の離れた2点目をクリックしてください。':'③ 円周上の別の側にある3点目をクリックしてください。');}else if(mode==='manual'){if(closed)return status('閉じた輪郭は「頂点を移動」で修正できます。描き直すには「輪郭を消去」。');save();points.push(p)}else if(mode==='auto'){save();seed=p;guessSettings();extract();}draw()};
c.onpointermove=e=>{if(drag>=0){points[drag]=position(e);draw()}};c.onpointerup=c.onpointercancel=()=>{drag=-1};
$('close').onclick=()=>{if(points.length<3)return status('3点以上指定してください。');save();closed=true;draw();status('輪郭を閉じました。寸法を確認してDXFを書き出せます。')};$('undo').onclick=()=>{clearTimeout(timer);adjusting=false;const prev=history.pop();if(prev){({points,coin,closed,seed,validTrace,detectedLight,mode}=prev);for(const id of ['threshold','polarity','smooth'])$(id).value=prev[id];$('thresholdValue').textContent=prev.threshold;setMode(mode);draw();status('ひとつ前の状態に戻しました。')}};$('clear').onclick=()=>{clearTimeout(timer);save();points=[];closed=false;seed=null;validTrace=true;draw();status('輪郭を消去しました。縮尺は引き続き使えます。')};$('plus').onclick=()=>setZoom(zoom*1.3);$('minus').onclick=()=>setZoom(zoom/1.3);$('fit').onclick=fit;
$('export').onclick=()=>{if(!validTrace||!closed||!scale())return;try{const text=Geometry.dxf(points,scale());const url=URL.createObjectURL(new Blob([text],{type:'application/dxf'})),a=document.createElement('a');a.href=url;a.download=name+'_R12.dxf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('DXFを書き出しました。CADで読み込む際も単位をmmにしてください。')}catch(e){status(e.message)}};
function guide(){
 let title='写真を選ぶか、サンプルで試しましょう',text='対象物と1円玉を同じ平面に置いて、真上から撮影します。';
 if(photo){title='写真の「型にしたい物の内側」をクリック';text='背景や1円玉ではなく、対象物の中央を1回クリックしてください。';
 if(mode==='calibrate'){title=['① 1円玉の円周上の1点目をクリック','② 円周上の離れた2点目をクリック','③ 円周上の別の側の3点目をクリック'][coin.length]||'3点を指定してください';text='円周を3か所に分けて、離れた点を選んでください。3点目で円が表示されます。';}
 else if(!validTrace){title='輪郭を取れませんでした';text='スライダーを調整するか、対象物の別の場所をクリック。オレンジの線は前の輪郭の参考表示です。';}
 else if(closed){title=mode==='edit'?'白い頂点をドラッグして修正':'✓ 輪郭が取れました';text=scale()?'寸法を確認して、実寸DXFを保存してください。':'緑の線が合っていれば「次へ」でサイズ合わせ。スライダーで調整もできます。';}
 else if(mode==='manual'){title='輪郭に沿って、順番に点をクリック';text='3点以上置いたら「手動の輪郭を閉じる」を押してください。前の輪郭は「元に戻す」で復元できます。';}}
 $('guideTitle').textContent=title;$('guideText').textContent=text;
 $('next').hidden=!(closed&&validTrace&&mode!=='calibrate');$('next').textContent=scale()?'↓ 実寸DXFを保存':'次へ：1円玉でサイズ合わせ';
 $('close').hidden=mode!=='manual'||closed;$('close').disabled=points.length<3;
 $('threshold').disabled=!seed||mode!=='auto';$('polarity').disabled=!seed||mode!=='auto';$('smooth').disabled=!seed||mode!=='auto';
 $('selection').textContent=seed?'● 対象選択済み · スライダーの変更を自動反映':'① 写真の対象物の内側をクリック';
 $('exportHint').textContent=!validTrace?'輪郭を取り直すと保存できます。':!closed?'先に対象物の輪郭を作ってください。':!scale()?'1円玉の円周を3点指定すると保存できます。':'R12形式・1図面単位 = 1 mm・閉じた外周1個。';
 for(const id of ['auto','manual','calibrate','fit','plus','minus'])$(id).disabled=!photo;
 $('edit').disabled=!points.length;$('undo').disabled=!history.length;$('clear').disabled=!points.length&&!seed;
 c.style.cursor=mode==='edit'?'grab':'crosshair';
}
function analysisImage(){const off=document.createElement('canvas'),r=Math.min(1,1200/Math.max(c.width,c.height));off.width=Math.round(c.width*r);off.height=Math.round(c.height*r);const x=off.getContext('2d');x.drawImage(photo,0,0,off.width,off.height);return x.getImageData(0,0,off.width,off.height)}
function guessSettings(){const im=analysisImage(),w=im.width,h=im.height,d=im.data;const brightness=(x,y)=>{const i=(Math.max(0,Math.min(h-1,Math.floor(y)))*w+Math.max(0,Math.min(w-1,Math.floor(x))))*4;return .299*d[i]+.587*d[i+1]+.114*d[i+2]};const values=[];for(let i=0;i<20;i++)values.push(brightness(i*w/20,0),brightness(i*w/20,h-1),brightness(0,i*h/20),brightness(w-1,i*h/20));values.sort((a,b)=>a-b);const bg=values[40],v=brightness(seed.x*w/c.width,seed.y*h/c.height);detectedLight=v>bg;$('threshold').value=Math.max(1,Math.min(254,Math.round((bg+v)/2)));$('thresholdValue').textContent=$('threshold').value;}
function extract(){if(!photo||!seed||mode!=='auto')return;try{const im=analysisImage(),w=im.width,h=im.height;const result=Geometry.trace(im.data,w,h,seed.x*w/c.width,seed.y*h/c.height,+$('threshold').value,$('polarity').value==='auto'?detectedLight:$('polarity').value==='light',+$('smooth').value).map(p=>({x:p.x*c.width/w,y:p.y*c.height/h}));points=result;closed=true;validTrace=true;status('✓ 緑の線が輪郭です。合っていれば「次へ」でサイズ合わせに進めます。')}catch(e){validTrace=false;status(e.message)}draw()}
let adjusting=false;
$('threshold').onpointerdown=()=>{if(seed&&!adjusting){save();adjusting=true}};
$('threshold').oninput=()=>{if(!seed)return;if(!adjusting){save();adjusting=true}clearTimeout(timer);$('thresholdValue').textContent=$('threshold').value;validTrace=false;draw();status('輪郭を更新しています…');timer=setTimeout(extract,100)};
$('threshold').onchange=()=>{clearTimeout(timer);extract();adjusting=false};
for(const id of ['polarity','smooth'])$(id).onchange=()=>{clearTimeout(timer);if(seed){save();extract()}};
$('next').onclick=()=>{if(scale())$('export').click();else $('calibrate').click()};
guide();
